### ISSUE TITLE
 Error on MEMRISE.garden.boxes "Cannot read property 'advance' of undefined"

### ISSUE THREAD

**Issue by MagTun** [cooljingle/memrise-ignore-previous#1]
Hi, 

I would like to use your script but there is an error on the ` MEMRISE.garden.boxes`. Apparently this property is not used anymore  but I wasn't able to find the new one. 

 `MEMRISE.garden.boxes.num` is also not used anymore. Any idea how to fix this? 

Thanks a lot!

**Comment by MagTun** [comment]
Any idea if it can be updated via `MEMRISE.garden.box.thinguser.ignored`?

**Comment by cooljingle** [comment]
I found a way to fix the script - but it only works on the current item rather than the previous. As such I've renamed the script/repo as part of the update.

https://github.com/cooljingle/memrise-ignore-current/raw/master/Memrise_Ignore_Current.user.js

**Comment by MagTun** [comment]
Thanks so much for fixing it!
It's even better now as that it's working on the current word. That's great!
